# 项目相关配置
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8089
  port: 8089
  servlet:
    # 应用的访问路径
    context-path: /
  # undertow 配置
  undertow:
    # HTTP post内容的最大大小。当值为-1时，默认值为大小是无限的
    max-http-post-size: -1
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 512
    # 是否分配的直接内存
    direct-buffers: true
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 8
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 256

navigate:
  # es连接下载路径
  esConnectParamPath: D:\study\code\project\esTool\backend\data\esConnectParam.json

# Spring配置
spring:
  application:
    name: "神的孩子都在歌唱-通用框架"
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
---


# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping:
  # 标题
  title: '接口文档'
  # 描述
  description: '神的孩子都在歌唱接口文档'
  # 版本
  version: '1.0.0'
  # 作者信息
  contact:
    name: ---
    email: ---
    url: 192.168.1.xxx


